// Code generated by protoc-gen-slogschema. DO NOT EDIT.
// source: user.proto

package main

import (
	"crypto/sha256"
	"fmt"
	"log/slog"
	"strconv"
)

func (x *Address) MarshalSLog() []slog.Attr {
	if x == nil {
		return nil
	}
	return []slog.Attr{
		{Key: "street", Value: slog.StringValue(x.GetStreet())},
		{Key: "city", Value: slog.StringValue(x.GetCity())},
		{Key: "country_code", Value: slog.StringValue(x.GetCountry())},
	}
}

func (x *User) MarshalSLog() []slog.Attr {
	if x == nil {
		return nil
	}
	return []slog.Attr{
		func() slog.Attr {
			if v := x.GetId(); !isEmpty(v) {
				sum := sha256.Sum256([]byte(fmt.Sprintf("%v", v)))
				return slog.String("id", fmt.Sprintf("sha256:%x", sum))
			}
			return slog.Attr{}
		}(),
		func() slog.Attr {
			sum := sha256.Sum256([]byte(fmt.Sprintf("%v", x.GetEmail())))
			return slog.String("email", fmt.Sprintf("sha256:%x", sum))
		}(),
		{Key: "name", Value: slog.StringValue(x.GetDisplayName())},
		func() slog.Attr {
			if v := x.GetPhone(); !isEmpty(v) {
				sum := sha256.Sum256([]byte(fmt.Sprintf("%v", v)))
				return slog.String("phone", fmt.Sprintf("sha256:%x", sum))
			}
			return slog.Attr{}
		}(),
		{Key: "role", Value: slog.StringValue(x.GetRole())},
		{Key: "created_at", Value: slog.TimeValue(x.GetCreatedAt().AsTime())},
		func() slog.Attr {
			if v := x.GetAddress(); !isEmpty(v) {
				return slog.Attr{Key: "address", Value: slog.GroupValue(v.MarshalSLog()...)}
			}
			return slog.Attr{}
		}(),
		func() slog.Attr {
			switch v := x.NotificationMethod.(type) {
			case *User_NotifyEmail:
				return slog.Attr{Key: "notify_email", Value: slog.StringValue(v.NotifyEmail)}
			case *User_NotifySms:
				return slog.Attr{Key: "notify_sms", Value: slog.StringValue(v.NotifySms)}
			}
			return slog.Attr{}
		}(),
		func() slog.Attr {
			elems := x.GetRoles()
			attrs := make([]slog.Attr, len(elems))
			for i, v := range elems {
				attrs[i] = slog.Attr{Key: strconv.Itoa(i), Value: slog.StringValue(v)}
			}
			return slog.Attr{Key: "roles", Value: slog.GroupValue(attrs...)}
		}(),
	}
}

func isEmpty(v any) bool {
	switch val := v.(type) {
	case string:
		return val == ""
	case bool:
		return !val
	case int32:
		return val == 0
	case uint32:
		return val == 0
	case int64:
		return val == 0
	case uint64:
		return val == 0
	case float32:
		return val == 0
	case float64:
		return val == 0
	default:
		return v == nil
	}
}
